#+CATEGORY: ecología, periodismodatos 
#+TAGS: territorio, espacio, contaminación
#+DESCRIPTION: La Bahía de Portmán
#+TITLE: Los restos de la tragedia: la tragedia
#+DATE: [2014-03-20 jue 12:00]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
http://www.albertonoguera.com/2008/08/la-baha-de-portmn.html

Julio de 1986 Greenpeace realiza esta espectacular acción aplaudida por cualquier persona sensata, se intento taponar el conducto de salida de la empresa Peñarroya que vertía residuos tóxicos en la bahía Portman, en Cartagena. Estos vertidos que se iniciaron en la mitad de la década de 1950 han provocado uno de los mayores desastres ecológicos de España. Gracias a este tipo de acciones de gran repercusión y otras muchas se consiguió la clausura de todos los vertidos en 1990, para entonces la bahía ya había desaparecido colmatada por los residuos tóxicos vertidos | Vía Greenpeace El Mediterráneo Coordinación Xavier Pastor

Según [[http://www.laopiniondemurcia.es/municipios/2011/07/16/foto-accion-greenpeace-portman-dio-vuelta-mundo/337434.html][reconoce Xavier Pastor]]. al no lograr tapar los tubos se produjo una salida de vertidos en abanico, con chorros de más de 30 metros -como se aprecia en la fotografía-, "cuya imagen dio la vuelta al mundo consiguiendo un impacto mayor del que esperábamos".
en 1984 cuando la organización ecologista internacional aterrizó en España abriendo su primera sed
#+CAPTION: Dos activistas de Greenpeace intentan parar los vertidos de la empresa Peñarroya en la Bahía de Portmán en 1986
#+LABEL: 
#+ATTR_HTML: alt="Dos activistas de Greenpeace intentan parar los vertidos de la empresa Peñarroya en la Bahía de Portmán en 1986"
http://i50.tinypic.com/ibdmpf.jpg

No al sellado
http://zepelin.net/manifestacion-bahia-de-portman/

España Directo:
http://www.youtube.com/watch?v=N127ng3N5g0#t=14

¿Te acuerdas? Historia de un desastre.
http://www.youtube.com/watch?v=86QJK1II4Mc

Portmán. La historia olvidada de un desastre
http://www.youtube.com/watch?v=ibl3CHh8-ZA
Trabajaron 100.000 esclavos en las minas que sacaban plata y que embarcaban en el Puerto Grande o Portus Magnus (Portmán) hacia Roma. La minería moderna rompió ese frágil equilibrio.
Vídeo sobre el desastre de Portmán y el LLano del Beal (R. de Murcia) a partir de fotografías diversas y trozos del documental "Portmán, a la sombra de Roberto".
Educación ambiental. 3º Educación Social, Universidad de Murcia

http://elpais.com/diario/1990/03/25/sociedad/638319602_850215.html
Cierre de la tubería.
Alfonso García Sánchez
http://www.empresia.es/persona/alfonso-garcia-sanchez/
http://simbiotika.com/cargo/ALFONSO-GARCIA-SANCHEZ
 y Mariano Roca Meroño,
http://www.empresia.es/persona/mariano-roca-aparicio/
 
Relaciones de los empresarios con los políticos locales y con José Antonio Roca y Tomás Oivo, Eduardo Zaplana y Luis de Rivero (Sacyr)
http://lasombradeaznar.blogspot.com.es/2007/05/valcrcel-se-ahoga-en-una-balsa-de.html

Juan Ramón Calero, PP y PADE, hablando claro sobre las mentiras del PP con el Plan Hidrológico Nacional y el trasvase Ebro-Segura
http://www.dailymotion.com/video/x1v5gb_calero

Noticia efeverde
http://www.efeverde.com/noticias/la-bahia-de-portman-manana-se-estudia-una-oferta-para-su-regeneracion/

50 millones de toneladas
Mayor desastre ecológico del Mediterráneo.
Se cortan los vertidos en 1990
Francisa Baraza, jefa de la demarcación de Costas de Murcia. Mezcla con s
Poster vuelo USA F56 del Vuelo americano de 1956 en la Cuenca del Segura, publicado por la Confederación Hidrográfica del Segura. Oficina de Planificación Hidrológica, Ministerio de Agricultura, Alimentación y Medio Ambiente. Con licencia CC 3.0 España Reconocimiento-Compartir Igual.

La reconversión en Cartagena
http://www.youtube.com/watch?v=UceaOz0E-oI

Kante Pinreliko, soy de kartagena
Todos los obreros tienen silicosis
http://www.youtube.com/watch?v=4513dpSXG9A

Alberto Noguera
https://es.answers.yahoo.com/question/index?qid=20091029170207AAHTI3T

http://nachobueno.wordpress.com/2011/07/21/el-desastre-natural-de-la-bahia-de-portman/
http://divergencias.typepad.com/divergencias/2005/05/baha_de_portman.html

http://www.carloslmarco.com/lecciones-que-nos-da-la-vida/historias-de-un-mito-la-destruccion-de-la-bahia-de-portman/




