#+DATE: [2013-11-17 dom 22:30]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: coop, economía, copyleft, cultura,evento
#+TAGS: ows, 15m, yosoy132, direngezi, indignadxs, indignados, toni negri, javier toret, tiago pimentel, ruasemrede, revoltas globais
#+DESCRIPTION:
#+TITLE: Encuentro de redes globales

Bernardo Gutiérrez comenta por la lista P2P-es que durante los días 18 y 19 de noviembre tendrá lugar en Sao Paulo (Brasil) el encuentro de redes globales, una oportunidad para presentarse "el nuevo sujeto político-social" surgido de las asambleas populares, colectivos, redes que llevan funcionando en Brasil desde el mes de junio.
Pretenden preparar la estrategia para 2014 y contrastar su experiencia con participantes del 15M (España), Occupy Wall Street y Occupy Sandy (EE.UU.), #YoSoy132 (México), #DirenGezi (Turquía) e indignadxs de Perú o Chile.

El lunes 18 participa Toni Negri. El Martes 20 Bernardo Sampa presenta junto con Javier Toret y Tiago Pimentel (de Interagentes) una lectura
tecnopolítica de las revueltas de Brasil conectadas con el mundo.


Acabo de postar esto en mi Face:
La tag de twitter será #RuasEmRede.  Que circule!!!!!

""""#RuasEmRede. As Revoltas Globais nas Redes e nas Ruas. Imperdível
encontro em São Paulo, segunda (18) e (19). Um encontro que o pensador
Toni Negri abrirá segunda com uma aula aberta. O encontro vai ter uma
conexão inédita dos movimentos brasileiros que ocuparam as ruas, câmaras e
redes de junho para cá, com redes globais como #15M, Occupy Wall Street,
#YoSoy132, Diren Gezi (Turquia), os Indignados peruanos que tomaram as
ruas no #TomaLaCalle ou os estudantes xilenos. Vai ter uma grande presença
das regiões do Brasil. Assembleia Popular Horizontal :: Belo Horizonte
(com Matheus S. Cherem, Paulo Rocha, Francisco Foureaux e mais), Fabricio
Rocha para falar do Movimento Belém Livre e dos agitos paraenses, Bruno
Rogens (Assembleia popular do Maranhão / Passe Livre), Pedro Mendes
(assembleia popular do largo), Jefferson de Souza Vasconcelos e Larissa
Bery ( Rio de Janeiro Rebelde), Jaqueline Pontes Dias (OcupaAles e
movimentos do Espírito Santo), Marcelo Branco de Porto Alegre e Janaina
Spode (CCCD POA), Jul Pagul de Brasília, Pablo Ortellado (São Paulo),
Claudio Tavares (Direitos Direitos Urbanos de Recife).... um grande bonde
internacional, com Javier Toret Medina (15M), Cláudia Cisneros (Peru),
Giovanna Roa Cadin (Xile), Begum Özden Firat (Diren Gezi, Turquia), Raul
Sanchez Cedillo (15M). Sofia Gallisá Muriente (Occupy, articuladora de
#OccupySandy), Laura Citali Murillo Cortes (#YoSOy132). Eu apresento com o
Toret e Tiago Tiago F. Pimentel uma leitura tecnopolítica dos protestos do
Brasil no contexto global. O mais bacana: esses ativistas todos ficam o
dia 20 em SP, dialogando, conspirando e achando o comum dos
#protestos2014" http://www.facebook.com/events/1423257257892107/?fref=ts

Bernardo Gutiérrez
Twitter: @bernardosampa / @codigoabiertocc / @futura_media
FuturaMedia.net
http://codigoabiertocc.wordpress.com/

https://scontent-a-lhr.xx.fbcdn.net/hphotos-prn2/1424387_592074877495457_1782363294_n.jpg
