#+BLOG: infotics
#+POSTID: 932
#+DATE: [2013-10-29 mar 16:56]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: coop, cultura, periodismo, evento
#+TAGS: crowdfunding, crowdjournalism, nuevos medios, periodistas, audiencia
#+DESCRIPTION: Información sensible es un medio abierto a periodistas para que propongan sus informaciones y el público lo financie. Los materiales son copyleft.
#+TITLE: Información sensible propuesta por periodistas y financiada por su audiencia

Por la lista de correo del grupo de Periodismo de Datos de Medialab descubro el proyecto [[http://www.informacionsensible.com][Información Sensible]], un medio digital con información de actualidad y reportajes de investigación que comenzó su andadura a principios de año.

#+CAPTION: La historia es nuestra y la hacen los pueblos, imagen de http://www.flickr.com/photos/jpazkual/
#+LABEL: La historia es nuestra y la hacen los pueblos, imagen de http://www.flickr.com/photos/jpazkual/
http://farm9.staticflickr.com/8145/7289931640_efeb0a3d14_z.jpg

El proyecto consta de dos partes. Por un lado, una redacción al uso que, como confiesan en las [[http://www.informacionsensible.com/faq.php][FAQs]], "no nace con la vocación de ser un medio de comunicación alternativo sino un medio de comunicación convencional con un nuevo modelo de negocio". Se comprometen a realizar una apuesta por el periodismo de calidad y por la información libre, sin cortapisas ni intermediarios, que ahora se ha hecho posible gracias a las nuevas tecnologías. En este sentido también, su otra cara y su "gran apuesta", una plataforma de /crowdfunding/ para periodistas que "elimina la posible presión o censura de anunciantes o grupos de interés, tanto públicos como privados".

El proyecto pretende que lxs lectorxs puedan financiar aquellos contenidos propuestos por lxs periodistas. El primer paso para lxs periodistas consiste en registrarse en la web. Luego, proponen temas a la redacción de *IS*, que valorará con el "único requisito que la información publicada sea de interés general, veraz y contrastada, independientemente de a quién afecte". Por ello, toman como modelo de funcionamiento para su línea editorial el [[http://www.informacionsensible.com/codeofethics.php][código deontológico de la FAPE]], consensuado entre las distintas entidades profesionales de toda España. Una vez aprobado por la redacción, lxs usuarixs registradxs en *IS* decidirán si apoyan o no ese contenido. Una vez que alcanza su financiación, el contenido se publica bajo licencia [[http://creativecommons.org/licenses/by-sa/3.0/deed.es][Creative Commons que permite la copia, modificación o redistribución del contenido]]. 

Los contenidos pueden ser de cuatro tipos: reportaje, gran reportaje, fotoperiodismo y otros proyectos informativos. El reportaje se valora por defecto en 350 euros. Si en un plazo de 10 días se consiguen los fondos necesarios, el reportaje tendrá luz verde y el dinero se destina a lxs periodistas que lo propusieron. Si se considera que el reportaje es más valioso por el tiempo de elaboración, se puede solicitar una financiación más elevada.

También tendrán cabida proyectos como documentales, libros, exposiciones fotográficas, proyectos de periodismo de datos y trabajos de cualquier otro género informativo. 

Lxs periodistas reciben en torno al noventa por ciento del dinero recaudado. *IS* percibe entre un cinco y un diez por ciento y la pasarela de pago entre un dos y un tres.

Los perfiles de lxs periodistas son públicos, a modo de currículos, para que tanto lxs lectores como personas de otros medios de comunicación puedan conocer sus trabajos y experiencia profesional. Podéis ver como ejemplo el [[http://www.informacionsensible.com/profileview.php?user%3D30][perfil de Carlos Torres]], actual guionista de Salvados.




