* TODO pasar de odt a orgmode /Open Data, la transparencia hecha negocio/ :opendata:open:data:carlos:iglesias:negocio:

* Entrevista con Carlos Iglesias acerca de /Open Data/

[[http://www.fundetec.es][Fundetec]] acaba de lanzar su [[http://www.fundetec.es/publicaciones/revista-fundetec-29-2o-cuatrimestre/][primer número en digital de su revista corporativa]] ([[http://www.fundetec.es/wp-content/uploads/2013/05/Revista-Fundetec-29.pdf][PDF]]). Para elaborar el reportaje sobre las oportunidades de negocio entrevistamos a Carlos Iglesias, consultor de /Open Data/ independiente. Reproducimos íntegramente la entrevista que nos sirvió de guía para realizar el reportaje. 

* Biografía

Carlos Iglesias ([[http://es.linkedin.com/in/carlosiglesiasmoro/][LinkedIn]], [[https://www.twitter.com/carlosiglesias][Twitter]]) cuenta con una amplia experiencia práctica en el campo del /Open Government Data/ (transparencia en los datos públicos) gracias a su participación en la preparación y puesta en marcha de más de veinte iniciativas locales, regionales y nacionales, incluyendo la metodología para los estudios de viabilidad de iniciativas /Open Data/ en países emergentes que utiliza la [[http://www.webfoundation.org][Web Foundation]], la definición estratégica y dirección técnica del [[http://datos.gob.es/datos/][Catálogo Nacional de Datos de España]] o la completa redefinición de la estrategia para la [[http://epsiplatform.eu/][ePSI Platform]], el punto de encuentro sobre *Reutilización de la Información del Sector Público en Europa*.

* Preguntas

** 1

*Pregunta*

La posibilidad de que tanto los ciudadanos como las empresas puedan acceder y utilizar los datos almacenados por las administraciones está permitiendo el nacimiento de un nuevo modelo de negocio basado en la creación de productos y servicios de valor añadido a partir de esta información pública. Se abren un sinfín de posibilidades a usuarios y desarrolladores para crear múltiples aplicaciones y negocios en la red. ¿Nos podía concretar alguna de esas posibilidades?

*Respuesta*

Desde mi punto de vista, el verdadero potencial reside en el hecho de que por mucho que se intente no creo que haya nadie capaz de concretar esas posibilidades, y eso es debido a que el concepto de la innovación aplicado al /Open Data/ se basa principalmente en dos premisas:
- El principio de las muchas mentes: "La mejor forma de utilizar tus datos se le ocurrirá a otro", de Jo Walsh y [[https://twitter.com/rufuspollock][Rufus Pollock]].
- La ley de Joy: "No importa quien seas, la mayoría de la gente inteligente trabaja para otro", de Bill Joy.

Sumando ambas premisas es cuando nos damos cuenta de que las posibilidades residen precisamente en unir la apertura de los datos con la creatividad de aquellos que los vayan a combinar y transformar para poder ser utilizados. No existen fórmulas mágicas, la clave fundamental sigue siendo la misma de siempre, pensar en cuáles son las necesidades de las personas y buscar la mejor manera posible de poder satisfacerlas, la única diferencia es que ahora tenemos la oportunidad de poder acceder cada día a más datos y a nuevas fuentes como las que proporcionan las redes sensoriales de las /Smart Cities/, lo que multiplica las posibilidades.

** 2

*P*

En este momento, en España, ¿cuáles son  las principales iniciativas y fuentes de datos en abierto disponibles?

*R*

En España contamos ya con unas [[http://datos.fundacionctic.org/sandbox/catalog/faceted/][veinte iniciativas a todos los niveles]]. A nivel nacional tenemos no sólo el [[http://datos.gob.es/datos/][Catálogo Nacional de Datos]]*, sino también con cierto [[http://datos.gob.es/datos/?q%3Dnode/145][marco legislativo]], una serie de [[http://datos.gob.es/datos/?q%3Dnode/2108][planes estratégicos]] en desarrollo, [[http://datos.gob.es/datos/?q%3Dtaxonomy/term/1538][guías prácticas]], un [[http://administracionelectronica.gob.es/recursos/pae_000023192.pdf][marco de interoperabilidad para la reutilización de recursos]] y [[http://datos.gob.es/datos/?q%3Dsaber-mas/guiasynormas/soporte][otras medidas de apoyo]] con el objetivo de conseguir que el número de conjuntos de datos disponibles vaya aumentando gradualmente tanto en cantidad como en calidad.

A nivel regional existen también múltiples iniciativas, desde las pioneras en [[http://opendata.euskadi.net/w79-home/eu/][Euskadi]], [[http://www.asturias.es/portal/site/webasturias/menuitem.a76385ecc651687bd9db8433f2300030/?vgnextoid%3D1a69b1ea17dfe210VgnVCM10000097030a0aRCRD&vgnextchannel%3De1f502a263b6e210VgnVCM1000002f030003RCRD&i18n.http.lang%3Des][Asturias]] o [[http://www20.gencat.cat/portal/site/dadesobertes][Cataluña]] hasta la más reciente en [[http://opendata.aragon.es/][Aragón]], y a nivel local ciudades como [[http://www.zaragoza.es/ciudad/risp/][Zaragoza]] y [[http://datos.gijon.es/][Gijón]] fueron las encargadas de abrir un camino al que se han ido sumando otras como las recién incorporadas [[http://pamplona.es/verPagina.asp?IdPag%3D1519][Pamplona]] y [[http://opendata.terrassa.cat/][Terrassa]].

Pero lo más importante es que el /Open Data/ sigue muy vivo y no hay prácticamente un mes en el que no se anuncie otra iniciativa. En lo poco que llevamos de año ya llevamos cuatro nuevas iniciativas y seguiremos sumando, porque estoy convencido que este será el año de las iniciativas en las ciudades y comenzaremos a ver cada vez más a lo largo del mundo.

** 3

*P*

¿Cómo y para qué pueden utilizar las empresas estos datos?

*R*

Todas las empresas utilizan datos en mayor o menor medida para su actividad diaria. La variedad de datos y su potencial es tan grande que el límite en cuanto a sus posibilidades de aplicación lo pone únicamente la imaginación.

Algunos datos son de aplicación más transversal, como la *Información Geográfica y la Meteorología*, y por tanto pueden ser de utilidad prácticamente para cualquier empresa o negocio. Otros datos pueden tener nichos de explotación mucho más específicos como por ejemplo los datos relacionados con la sanidad o las investigaciones clínicas, pero aun así al tratar cuestiones de claro interés público pueden dar lugar también a servicios con un mercado potencial muy amplio.

** 4

¿Cuáles son los datos más utilizados y a partir de ellos qué servicios están surgiendo?

Los datos que suscitan un mayor interés suelen ser aquellos relacionados con información geográfica y cartografía, económica, jurídica y legal, estadística y sociodemografía, transportes, sanidad, educación, empleo o seguridad.

Sin embargo, no todos están siempre disponibles, así que dependiendo del país y el caso concreto los datos más utilizados pueden ser unos u otros. En principio, los datos relacionados con la información geográfica son con diferencia los más demandados y al mismo tiempo los más utilizados a nivel global, a lo que contribuye sin duda que las estimaciones indican que aproximadamente un 80% de las decisiones que deben tomar tanto las autoridades públicas como las grandes empresas cuentan con un componente geoespacial. Por otro lado, ese éxito es debido también en buena parte a la [[http://inspire.jrc.ec.europa.eu/][directiva INSPIRE]], que ha conseguido proporcionar un marco común para las infraestructuras del ámbito geoespacial a nivel europeo, dando así lugar al caldo de cultivo ideal para el éxito en la reutilización.

** 5

*P*

¿Es difícil usarlos?

*R*

Conseguir que los datos estén disponibles, y que además se publiquen bajo unas condiciones de uso que permitan su reutilización es ya un gran paso. Sin embargo, en muchos casos el tratamiento de los datos resulta un proceso bastante más costoso de lo que sería razonable debido a que no se publican de la forma adecuada. Esto da lugar a que se tenga que invertir tiempo y recursos en su tratamiento que serían mucho más productivos si se utilizasen para el análisis posterior, que es la parte del proceso donde realmente se genera valor.

Utilizar formatos que sean legibles por las máquinas, adoptar vocabularios estandarizados para los datos y documentarlos adecuadamente son acciones imprescindibles para facilitar la reutilización, eliminar barreras de entrada a nuevas empresas para que puedan crear sus productos o servicios y conseguir que exista un mercado de datos vivo y dinámico.

** 6

*P*

¿Hay que tener conocimientos específicos o una base tecnológica para utilizarlos?

*R*

La gran variedad de datos existente, las posibilidades que ofrecen los múltiples formatos disponibles y la proliferación de herramientas que facilitan o incluso automatizan en parte su tratamiento hacen que hoy en día prácticamente cualquiera pueda experimentar con los datos si se lo propone y le dedica un poco de tiempo.

Por supuesto, cuanto más complejos sean los datos o el análisis que queramos realizar sobre ellos mayores serán también los conocimientos específicos que debemos tener para poder sacarles partido, y es ahí donde surge la necesidad de todo un mercado especializado de intermediarios de datos o infomediarios.

No hay que olvidar que el análisis y tratamiento de los datos es toda una ciencia por sí misma, que de hecho se viene denominando /Data Science/, y que implica la participación de múltiples y variados perfiles para poder exprimirle todo el jugo a los datos, desde profesionales de las matemáticas y la estadística hasta especialistas en algoritmos de tratamiento de datos o expertos en su visualización, pasando por supuesto por las personas capacitadas para el estudio de la materia específica que se esté analizando en cada caso, ya sea sanidad, educación, transportes, etc.

Y es que no es lo mismo hacer una aplicación para móvil que nos indique cuáles son las [[http://demos.geoactio.es/farmacias/][farmacias de guardia]] que proponerse realizar un [[http://www.nature.com/news/open-data-project-aims-to-ease-the-way-for-genomic-research-1.10507][estudio sobre el genoma humano]] por ejemplo. Aunque en ambos casos estaremos creando nuevos productos y servicios útiles para la sociedad y basados en el Open Data, los conocimientos requeridos, los medios necesarios para llevarlos a cabo y los beneficios obtenidos en uno y otro caso serán obviamente muy distintos.

** 7

*P*

En este momento, ¿qué número de empresas han desarrollado en nuestro país algún servicio a partir de estos datos públicos?

*R*

Ese es un dato que es difícil de estimar, debido a que no se cuenta con ningún censo oficial de referencia, y [[opencorporates.com/downloads/eu_company_data_report.pdf][el hecho de que nuestro registro mercantil sea un conjunto de datos completamente cerrado]] tampoco ayuda a facilitar este tipo de análisis.

En el caso de España se suele tomar como referencia el [[http://www.ontsi.red.es/ontsi/es/estudios-informes/estudio-de-caracterizaci%25C3%25B3n-del-sector-infomediario-en-espa%25C3%25B1-edici%25C3%25B3n-2012][estudio del sector infomediario]] realizado por el *ONTSI*, que en su última edición realizó un censo de más de 150 empresas en el sector. Sin embargo, mi propia experiencia me indica que es mucho más que probable que la realidad del mercado sea considerablemente mayor, ya que el censo utilizado no es exhaustivo y existe todo un mercado paralelo de actividades relacionadas con los datos que actualmente no se recogen y que es difícil de cuantificar.

Por otro lado, nos encontramos en una fase en la que el mercado está todavía tomando forma, y una vez se empiecen a poner en marcha medidas adicionales que aporten mayor seguridad y sostenibilidad al sector, como por ejemplo la unificación de las licencias de uso o la aplicación de compromisos de servicio que garanticen la disponibilidad de los datos y eliminen la incertidumbre para los emprendedores que quieran montar sus servicios sobre unos determinados datos.

** 8

*P*

¿Qué volumen de negocio generan?

*R*

Se han realizado [[http://ec.europa.eu/information_society/policy/psi/docs/pdfs/report/psi_final_version_formatted.docx][varios estudios a nivel internacional]] al respecto y, aunque las cifras no siempre coinciden, lo que sí que tienen todos en común es que las estimaciones son siempre optimistas y los volúmenes de negocio son realmente considerables.

En el caso de España nuevamente podemos tomar como referencia inicial el estudio del *ONTSI* que hace unas estimaciones de un volumen de negocio de unos 500 millones de euros para el conjunto del sector. Sin embargo, es más que probable que la realidad del mercado sea considerablemente mayor, ya que al hecho de que el censo de empresas no sea exhaustivo hay que sumarle que no se exploran en profundidad posibles sinergias con otros sectores. Por ejemplo, la *Asociación Multisectorial de la Información* (ASEDIE) hace unas estimaciones de cifras de negocio en torno a 50.000 millones de euros si tenemos en cuenta también las potenciales sinergias entre el Open Data y la industria de los contenidos digitales, lo que podría llegar a suponer hasta un 5% del PIB nacional.

Además, en muchos casos los modelos de negocio todavía no están claramente definidos y se siguen [[http://www.theodi.org/guide/how-make-business-case-open-data][explorando las posibilidades]], por lo que a medida que el mercado vaya alcanzado también una mayor madurez en ese sentido es previsible que eso se haga notar también en el volumen de negocio.

Por supuesto, e independientemente de todas estas cifras económicas, tampoco podemos olvidar que gracias al Open Data se generan también otra serie de valores intangibles para la sociedad como mejoras en la transparencia del Gobierno y la participación de los ciudadanos.

** 9

*P*

Territorialmente, ¿en qué comunidad autónoma hay un mayor grado de reutilización de esta información o mayor número de empresas?

*R*

Dado que Internet y las nuevas tecnologías son los habilitadores que facilitan las tareas de compartir y analizar grandes cantidades de información, es un hecho que las empresas cuya base de negocio consiste en la reutilización de datos suelen tener también un componente tecnológico considerable. Como es lógico, entonces, se detecta también una mayor concentración de empresas reutilizadoras allí donde también se encuentra una mayor concentración de empresas con estas características, es decir, principalmente, Madrid y Cataluña.

En cuanto a los lugares dónde se puede concentrar más la reutilización, yo diría que el interés por los datos es global y por tanto no creo que exista tal concentración, si bien como es evidente en cada caso el grado de reutilización será directamente proporcional a la cantidad de información disponible, el valor de los datos publicados y el ecosistema de reutilizadores que se forme a su alrededor. Si tenemos en cuenta esas tres variables, quizás podamos destacar nuevamente a Cataluña, puesto que cuenta ya con un gran número de iniciativas que publican algunos datos realmente interesantes y con un [[http://oer.uoc.edu/cursOpenData/qui-som/][completo ecosistema de reutilización]] vivo, activo y coordinado, elementos que en su conjunto a día de hoy no encontramos en ninguna otra región.

** 10

*P*

La Comisión Europea ha estrenado este año un [[http://open-data.europa.eu/open-data/][nuevo portal de datos abiertos]] en el que quiere que participen todos los estados miembros con el objetivo de crear el mayor repositorio de datos abiertos de la Unión Europea. ¿Puede suponer esto el definitivo impulso para este sector de contenidos que llaman infomediario?

*R*

El portal que acaba de publicar la Comisión Europea para facilitar el acceso a la información de sus propias instituciones es un nuevo paso hacia delante dentro de la política global que lleva ya a cabo desde hace algunos años para fomentar la reutilización de la información de los organismos públicos.

Dentro de esa misma [[http://carlosiglesias.es/blog/2012/10/avances-de-la-comision-europea-en-materia-de-open-data-y-risp/][política de promoción del Open Data]] en el ámbito Europeo, está previsto también que este mismo año salga a concurso un nuevo portal pan-europeo en el que los distintos países miembro puedan federar sus datos formando así un macrocatálogo de información pública a nivel europeo, así como con otras medidas que incluyen acciones para la publicación de más conjuntos de datos y el fomento de las tecnologías de datos enlazados o la difusión y sensibilización en el sector público a través de la [[http://www.paueducation.com/en/content/pau-education-selected-to-renew-the-epsi-platform][renovación de la ePSI Platform]].

Desde luego todas estas medidas son pasos positivos para el impulso de la economía en torno al /Open Data/, ya que supondrán una mayor disponibilidad de datos de alto valor y en un formato que facilite su explotación, pero en mi opinión el impulso más importante y puede que definitivo será la puesta en marcha de la [[cordis.europa.eu/fp7/ict/content-knowledge/docs/open-data-reuse-incubator4-3-a.pdf][Incubadora Open Data Europea]], que de forma similar al trabajo realizado por el [[http://www.theodi.org/][Open Data Institute]] en el Reino Unido, trabajará para facilitar a las empresas los datos que necesitan y los medios para poder llevar a cabo sus proyectos. Espero que algún día podamos ver esos mismos modelos replicados también en España, puesto que creo que las [[http://carlosiglesias.es/blog/2012/07/open-government-open-data-y-reutilizacion-en-la-agenda-digital-de-espana/][medidas relacionadas con el Gobierno Abierto y el Open Data incluidas en la Agenda Digital]] van por el camino correcto, pero echo también en falta [[http://carlosiglesias.es/blog/2012/09/condiciones-minimas-para-la-estrategia-risp-de-la-agenda-digital-de-espana/][otras actuaciones que las complementen]].


